import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    Box,
    Button,
    Container,
    Grid,
    Paper,
    Typography,
    Card,
    CardContent,
    CardActions,
    Chip,
    Stack,
    IconButton,
    useTheme,
} from '@mui/material';
import {
    School as SchoolIcon,
    TrendingUp as TrendingUpIcon,
    Business as BusinessIcon,
    Analytics as AnalyticsIcon,
    PlayArrow as PlayArrowIcon,
    ArrowForward as ArrowForwardIcon,
    CheckCircle as CheckCircleIcon,
} from '@mui/icons-material';

const features = [
    {
        title: 'AI-Powered Questions',
        description: 'Get personalized aptitude questions generated by AI based on your weak areas and target companies.',
        icon: <SchoolIcon sx={{ fontSize: 40 }} />,
        color: 'primary.main',
    },
    {
        title: 'Progress Tracking',
        description: 'Monitor your performance with detailed analytics and identify areas for improvement.',
        icon: <TrendingUpIcon sx={{ fontSize: 40 }} />,
        color: 'secondary.main',
    },
    {
        title: 'Company Specific',
        description: 'Practice questions tailored to specific companies and their recruitment patterns.',
        icon: <BusinessIcon sx={{ fontSize: 40 }} />,
        color: 'success.main',
    },
    {
        title: 'Smart Analytics',
        description: 'Get insights into your performance, weak areas, and personalized recommendations.',
        icon: <AnalyticsIcon sx={{ fontSize: 40 }} />,
        color: 'warning.main',
    },
];

const branches = ['Mechanical', 'Civil', 'Electrical', 'Electronics', 'IT', 'Computer Science'];

export default function HomePage() {
    const navigate = useNavigate();
    const theme = useTheme();
    const [selectedBranch, setSelectedBranch] = useState('');

    const handleGetStarted = () => {
        if (selectedBranch) {
            navigate('/register', { state: { branch: selectedBranch } });
        } else {
            navigate('/register');
        }
    };

    const handlePracticeNow = () => {
        navigate('/practice');
    };

    return (
        <Container maxWidth="xl">
            {/* Hero Section */}
            <Box
                sx={{
                    py: 8,
                    textAlign: 'center',
                    background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.primary.dark} 100%)`,
                    borderRadius: 4,
                    color: 'white',
                    mb: 6,
                    px: 4,
                }}
            >
                <Typography variant="h2" component="h1" gutterBottom sx={{ fontWeight: 'bold' }}>
                    Master Aptitude. Ace Placements.
                </Typography>
                <Typography variant="h5" component="h2" gutterBottom sx={{ mb: 4, opacity: 0.9 }}>
                    AI-powered placement preparation platform for engineering students
                </Typography>

                <Box sx={{ display: 'flex', justifyContent: 'center', gap: 2, mb: 4 }}>
                    <Button
                        variant="contained"
                        size="large"
                        onClick={handleGetStarted}
                        sx={{
                            bgcolor: 'white',
                            color: 'primary.main',
                            '&:hover': { bgcolor: 'grey.100' },
                            px: 4,
                            py: 1.5,
                        }}
                    >
                        Get Started Free
                    </Button>
                    <Button
                        variant="outlined"
                        size="large"
                        onClick={handlePracticeNow}
                        sx={{
                            borderColor: 'white',
                            color: 'white',
                            '&:hover': { borderColor: 'grey.300', bgcolor: 'rgba(255,255,255,0.1)' },
                            px: 4,
                            py: 1.5,
                        }}
                    >
                        <PlayArrowIcon sx={{ mr: 1 }} />
                        Practice Now
                    </Button>
                </Box>

                {/* Branch Selection */}
                <Box sx={{ mt: 6 }}>
                    <Typography variant="h6" gutterBottom>
                        Select your engineering branch
                    </Typography>
                    <Stack direction="row" spacing={1} justifyContent="center" flexWrap="wrap">
                        {branches.map((branch) => (
                            <Chip
                                key={branch}
                                label={branch}
                                onClick={() => setSelectedBranch(branch)}
                                color={selectedBranch === branch ? 'primary' : 'default'}
                                variant={selectedBranch === branch ? 'filled' : 'outlined'}
                                sx={{ m: 0.5, color: selectedBranch === branch ? 'white' : 'inherit' }}
                            />
                        ))}
                    </Stack>
                </Box>
            </Box>

            {/* Features Section */}
            <Typography variant="h3" component="h2" gutterBottom sx={{ textAlign: 'center', mb: 6 }}>
                Why Choose AptiMaster AI?
            </Typography>
            <Grid container spacing={4} sx={{ mb: 8 }}>
                {features.map((feature, index) => (
                    <Grid item xs={12} md={6} lg={3} key={index}>
                        <Card
                            sx={{
                                height: '100%',
                                display: 'flex',
                                flexDirection: 'column',
                                transition: 'transform 0.3s, box-shadow 0.3s',
                                '&:hover': {
                                    transform: 'translateY(-8px)',
                                    boxShadow: 6,
                                },
                            }}
                        >
                            <CardContent sx={{ flexGrow: 1, textAlign: 'center' }}>
                                <Box sx={{ color: feature.color, mb: 2 }}>
                                    {feature.icon}
                                </Box>
                                <Typography variant="h5" component="h3" gutterBottom>
                                    {feature.title}
                                </Typography>
                                <Typography color="text.secondary">
                                    {feature.description}
                                </Typography>
                            </CardContent>
                            <CardActions sx={{ justifyContent: 'center', pb: 2 }}>
                                <Button endIcon={<ArrowForwardIcon />}>Learn More</Button>
                            </CardActions>
                        </Card>
                    </Grid>
                ))}
            </Grid>

            {/* Stats Section */}
            <Paper sx={{ p: 4, mb: 8, borderRadius: 4 }}>
                <Grid container spacing={4} alignItems="center">
                    <Grid item xs={12} md={6}>
                        <Typography variant="h4" component="h3" gutterBottom>
                            Join 10,000+ Students Already Improving Their Skills
                        </Typography>
                        <Typography variant="body1" paragraph>
                            AptiMaster AI has helped students from top engineering colleges secure placements in their dream companies.
                        </Typography>
                        <Button
                            variant="contained"
                            size="large"
                            onClick={() => navigate('/register')}
                            endIcon={<ArrowForwardIcon />}
                        >
                            Start Your Journey
                        </Button>
                    </Grid>
                    <Grid item xs={12} md={6}>
                        <Grid container spacing={2}>
                            {[
                                { label: 'Questions Solved', value: '500K+' },
                                { label: 'Average Score Improvement', value: '35%' },
                                { label: 'Placement Success Rate', value: '85%' },
                                { label: 'Active Users', value: '10K+' },
                            ].map((stat, index) => (
                                <Grid item xs={6} key={index}>
                                    <Paper
                                        sx={{
                                            p: 3,
                                            textAlign: 'center',
                                            bgcolor: 'background.default',
                                            borderRadius: 3,
                                        }}
                                    >
                                        <Typography variant="h3" component="div" color="primary" gutterBottom>
                                            {stat.value}
                                        </Typography>
                                        <Typography variant="body2" color="text.secondary">
                                            {stat.label}
                                        </Typography>
                                    </Paper>
                                </Grid>
                            ))}
                        </Grid>
                    </Grid>
                </Grid>
            </Paper>

            {/* CTA Section */}
            <Box sx={{ textAlign: 'center', py: 6 }}>
                <CheckCircleIcon sx={{ fontSize: 60, color: 'success.main', mb: 2 }} />
                <Typography variant="h4" component="h3" gutterBottom>
                    Ready to boost your placement chances?
                </Typography>
                <Typography variant="body1" color="text.secondary" paragraph sx={{ maxWidth: 600, mx: 'auto', mb: 4 }}>
                    Join thousands of engineering students who are already preparing smarter with AptiMaster AI.
                </Typography>
                <Button
                    variant="contained"
                    size="large"
                    onClick={handleGetStarted}
                    sx={{ px: 6, py: 1.5, fontSize: '1.1rem' }}
                >
                    Get Started For Free
                </Button>
            </Box>
        </Container>
    );
}